// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzBOgFrx2tpaPwg0EhF_BRcFu6aw143fo',
    appId: '1:411672267284:web:3b22693771bf465c4a3501',
    messagingSenderId: '411672267284',
    projectId: 'helping-hands-834db',
    authDomain: 'helping-hands-834db.firebaseapp.com',
    storageBucket: 'helping-hands-834db.appspot.com',
    measurementId: 'G-9DBR4K7KBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiY4ZxynMo5tTJ0BuhNTaaYTej0y5mfYQ',
    appId: '1:411672267284:android:ea82a436eb97a5874a3501',
    messagingSenderId: '411672267284',
    projectId: 'helping-hands-834db',
    storageBucket: 'helping-hands-834db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcFGeoioZsEzMlCcR83xyj9y6eryAqUSk',
    appId: '1:411672267284:ios:01054283dc2df89a4a3501',
    messagingSenderId: '411672267284',
    projectId: 'helping-hands-834db',
    storageBucket: 'helping-hands-834db.appspot.com',
    iosBundleId: 'com.example.helpingHands',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcFGeoioZsEzMlCcR83xyj9y6eryAqUSk',
    appId: '1:411672267284:ios:01054283dc2df89a4a3501',
    messagingSenderId: '411672267284',
    projectId: 'helping-hands-834db',
    storageBucket: 'helping-hands-834db.appspot.com',
    iosBundleId: 'com.example.helpingHands',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzBOgFrx2tpaPwg0EhF_BRcFu6aw143fo',
    appId: '1:411672267284:web:cc968d4866c56a4b4a3501',
    messagingSenderId: '411672267284',
    projectId: 'helping-hands-834db',
    authDomain: 'helping-hands-834db.firebaseapp.com',
    storageBucket: 'helping-hands-834db.appspot.com',
    measurementId: 'G-9J882E5ZV8',
  );
}
